language: java
matrix:
  include:
# Java 8
    - jdk: oraclejdk8
# Java 9
    - jdk: oraclejdk9
      env: JDK_RELEASE='Oracle JDK 9'
# Java 11
    - env: JDK_RELEASE='Oracle JDK 11'
      install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -f 11 -l GPL
# Java 13
    - env: JDK_RELEASE='Oracle JDK 13'
      install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -f 13 -l GPL

#install: mvn install clirr:check
install: mvn install
after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=radiobrowser4j
