language: java
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk10
    - jdk: openjdk11
# Java 13
    - env: JDK_RELEASE='Oracle JDK 13'
      install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -f 13 -l GPL

#install: mvn install clirr:check
install: mvn install
after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=radiobrowser4j
