version: 2
shared: &shared
  steps:
    - checkout
    - restore_cache:
        key: maven-{{ checksum "pom.xml" }}
    - run:
        name: Maven Get Dependencies
        command: mvn dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: maven-{{ checksum "pom.xml" }}
    - run:
        name: Maven Build and test
        command: mvn clean package
    - run:
        name: Maven Install
        command: mvn install

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *shared
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk
    <<: *shared

workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
