name: Deploy Snapshot SonaType OSS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SECRETS: ${{ secrets }}

jobs:
  deploy-to-sonatype-oss:
    uses: sfuhrm/github_workflows/.github/workflows/maven-deploy-snapshot-sonatype-oss.yml@main
    with:
      sonatype_user: ${{ SECRETS.SONATYPE_USER }}
      sonatype_password: ${{ SECRETS.SONATYPE_PASSWORD }}
