name: Deploy Snapshot SonaType OSS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  deploy-to-sonatype-oss:
    uses: sfuhrm/github_workflows/.github/workflows/maven-deploy-snapshot-sonatype-oss.yml@main
    with:
      sonatype_user: ${{ env.SONATYPE_USER }}
      sonatype_password: ${{ env.SONATYPE_PASSWORD }}
